apiVersion: v1
kind: Secret
metadata:
  name: sample-job-secret
  namespace: default
data:
  servicebus-queue: cHJpbWFyeQ==
  servicebus-connectionstring: RW5kcG9pbnQ9c2I6Ly9zYW5hcmF5YWJ1cy5zZXJ2aWNlYnVzLndpbmRvd3MubmV0LztTaGFyZWRBY2Nlc3NLZXlOYW1lPVJvb3RNYW5hZ2VTaGFyZWRBY2Nlc3NLZXk7U2hhcmVkQWNjZXNzS2V5PWtOUTRvU0Q4SE5BdHZGOTVwa1hycVBqSE5lL0I3ZmdpOG1IVW5ESmVpQmc9